### ISSUE TITLE
DRY .smoke class

### ISSUE THREAD

**Issue by Maaike0904** [Nazneen05x/back-to-static-creative-coding#13]
Je hebt 2x .smoke gebruikt (DRY)
https://github.com/Nazneen05x/back-to-static-creative-coding/blob/6c3fdc68f2663dc606a4668ba940cc8a3c054f99/src/routes/overons/%2Bpage.svelte#L80-L85

**Comment by Nazneen05x** [comment]
Thank you! aangepast!
