### ISSUE TITLE
DRY mediaquery

### ISSUE THREAD

**Issue by Maaike0904** [Nazneen05x/back-to-static-creative-coding#14]
Deze waardes heb je al eerder benoemd en blijven hetzelfde, dus je kan die weg laten
https://github.com/Nazneen05x/back-to-static-creative-coding/blob/6c3fdc68f2663dc606a4668ba940cc8a3c054f99/src/routes/kennisclips/%2Bpage.svelte#L70-L72

**Comment by Nazneen05x** [comment]
Thank you! aangepast!
